[build]
  functions = "netlify/functions"
  publish = "client"

[dev]
  functions = "netlify/functions"
  publish = "client"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
